name: Project Orion CLI Build

on:
  push:
    branches: [ "main" ]

jobs:

  release:
    runs-on: windows-latest
    name: "Release CLI"
    needs: build
    
    steps:
      - name: Download built CLI
        uses: actions/download-artifact@v2
        with:
          name: project-orion-cli
      - name: View content for debugging
        run: ls -R
      - name: Create new GitHub release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: CI Release ${{ github.run_number }}
      - name: Zip CLI
        uses: thedoctor0/zip-release@master
        with:
          filename: project_orion_cli.zip
      - name: Upload CLI to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./project_orion_cli.zip
          asset_name: project-orion-cli-v${{ github.run_number }}.zip
          asset_content_type: application/zip

  build:
    name: "Build CLI"

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Project_Path: ProjectOrionCLI\ProjectOrionCLI.csproj
      Build_Directory: .\CLIRelease
      Configuration: Release
      Platform: Any CPU
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Restore the application
      run: msbuild $env:Project_Path /t:Restore /p:Configuration=$env:Configuration /p:Platform=$env:Platform /p:OutDir=$env:Build_Directory

    # Build the CLI project
    - name: Build the CLI project
      run: msbuild $env:Project_Path /p:Configuration=$env:Configuration /p:Platform=$env:Platform /p:OutDir=$env:Build_Directory

    # Upload the MSIX package: https://github.com/marketplace/actions/upload-a-build-artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: project-orion-cli
        path: ${{ env.Build_Directory }}
